# Generated by Django 4.0.5 on 2022-12-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bst', models.TimeField(verbose_name='%H:%M')),
                ('bet', models.TimeField(verbose_name='%H:%M')),
                ('ppd', models.TimeField(verbose_name='%H:%M')),
            ],
        ),
        migrations.CreateModel(
            name='loginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=12)),
                ('dateTime', models.DateTimeField()),
                ('otp', models.CharField(max_length=10)),
            ],
        ),
    ]
